[project]
name = "solana-launchpads-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.9.4",
    "pandas>=2.3.0",
    "tabulate>=0.9.0",
]
